In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumpPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [13]:
a2 = np.array([[1,2,3],
               [4,5,6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [15]:
a3.shape

(3, 2, 3)

In [16]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays 

In [21]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [23]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2,3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[5, 7, 2, 5, 6],
       [7, 9, 8, 7, 1],
       [5, 1, 4, 0, 9]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.72074351, 0.55733274, 0.77821282],
       [0.71036684, 0.43555233, 0.88661182],
       [0.17659792, 0.43213245, 0.48056295],
       [0.15663633, 0.3210806 , 0.87220482],
       [0.31705611, 0.69503593, 0.71023607]])

In [35]:
random_array_2.shape

(5, 3)

In [36]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.80947302, 0.13619772, 0.27615618],
       [0.92702135, 0.35301262, 0.67688949],
       [0.72808959, 0.23711724, 0.54035169],
       [0.75164975, 0.85937266, 0.01110733],
       [0.12176767, 0.68546376, 0.46528854]])

In [44]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [48]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [40]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [49]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1

array([1, 2, 3])

In [51]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [53]:
a1[0]

1

In [54]:
a2[0]

array([1., 2., 3.])

In [55]:
a3.shape

(3, 2, 3)

In [56]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a2[1]

array([4. , 5. , 6.5])

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [59]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [60]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [61]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [64]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating & Comparing arrays

# Arithmetic

In [65]:
a1

array([1, 2, 3])

In [67]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [68]:
a1 + ones

array([2., 3., 4.])

In [69]:
a1 - ones

array([0., 1., 2.])

In [70]:
a1 * ones

array([1., 2., 3.])

In [73]:
a1

array([1, 2, 3])

In [71]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [72]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [74]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [75]:
a2 * a3

array([[[  1.,   4.,   9.],
        [ 16.,  25.,  39.]],

       [[  7.,  16.,  27.],
        [ 40.,  55.,  78.]],

       [[ 13.,  28.,  45.],
        [ 64.,  85., 117.]]])

In [76]:
a1 / ones

array([1., 2., 3.])

In [78]:
a2 / a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.16666667]])

In [79]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [81]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [80]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [82]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [83]:
np.add(a1, ones)

array([2., 3., 4.])

In [92]:
a1

array([1, 2, 3])

In [91]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [90]:
a1 / 2

array([0.5, 1. , 1.5])

In [93]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [88]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])

In [85]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [86]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [94]:
listy_list = [1,2,3]
type(listy_list)

list

In [95]:
sum(listy_list)

6

In [96]:
a1

array([1, 2, 3])

In [97]:
type(a1)

numpy.ndarray

In [98]:
sum(a1)

6

In [99]:
np.sum(a1)

6

Use Python's methods  (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`)

In [100]:
# Create a massive NumPy array
massive_array = np.random.random(100_000)
massive_array.size

100000

In [101]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [102]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

7.51 ms ± 218 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.5 µs ± 620 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [103]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [104]:
np.mean(a2)

3.5833333333333335

In [105]:
np.max(a2)

6.5

In [106]:
np.min(a2)

1.0

In [107]:
np.std(a2)

1.8352262954621035

In [108]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.368055555555556

In [109]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8352262954621035